language: node_js
node_js:
  - "10.16.0"
script:
  - npm run build
after_success:
  - npm run deploy
notifications:
  email:
    recipients:
      - i@lenconda.top
    on_success: always
    on_failure: always
    