language: node_js
node_js:
  - "10.0"
before_script:
  - npm run build
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    recipients:
      - i@lenconda.top
    on_success: always
    on_failure: always
    