language: node_js
node_js:
  - "10.0"
deploy:
  provider: script
  script: node ./deploy.js
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    recipients:
      - i@lenconda.top
    on_success: always
    on_failure: always
    